name: Post-Merge Actions-Backstage-API-Invoke
'on':
  pull_request:
    types:
      - closed
jobs:
  merged_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Invoke API
        run: >
          curl -X POST
          "https://backstage-developer-hub-jaladhi-rhdh.pes-dev-e6615681e74d1ae8dcbb77cfdab239d6-0000.eu-de.containers.appdomain.cloud/api/deploy-cloud-blueprint/deploy-blueprint"
          \            
            -H "Content-Type: application/json"
